### ISSUE TITLE
Outdated dependencies are failing

### ISSUE THREAD

**Issue by hugoeanogueira** [eiriklv/react-masonry-mixin#4]
Hi, after a few weeks of using your package, a fresh install started throwing errors during the build process, because one of your dependencies was not finding `matches-selector`.

I think that the `outlayer` module, used in your `masonry` dependency is outdated, because desandro updated his `matches-selector` package name to `desandro-matches-selector` in [version 1.0.3](https://github.com/desandro/matches-selector/commit/2d7702eab3393838e8098971a03cbec3fe7f5891#diff-4) (npm creates the desandro-matches-selector instead of matches-selector folder).

Maybe you could update your dependencies (not sure if you may use the original packages instead of the forks) to fix this issue.

Thanks!

**Comment by Gee63** [comment]
Having the same error. Any feedback or suggestions?

**Comment by marcelopereirascmspain** [comment]
I ran into the same issue today.
You can update this piece of code on
lines 993 and 1004 of
react-masonry-mixin/node_modules/masonry/node_modules/outlayer/outlayer.js
adding "desandro-" to the module name

```
if (typeof exports === 'object') {
  // CommonJS
  module.exports = outlayerDefinition(
    require('jquery'),
    require('eventie'),
    require('doc-ready'),
    require('eventemitter'),
    require('get-size'),
    require('desandro-matches-selector'),
    require('./item')
  );
} else if ( typeof define === 'function' && define.amd ) {
  // AMD
  define( [
      'jquery',
      'eventie/eventie',
      'doc-ready/doc-ready',
      'eventEmitter/EventEmitter',
      'get-size/get-size',
      'desandro-matches-selector/matches-selector',
      './item'
    ],
    outlayerDefinition );
```

**Comment by Gee63** [comment]
@marcelopereirascmspain worked :) Thank you!

**Comment by eiriklv** [comment]
@hugoeanogueira @Gee63 @marcelopereirascmspain @joernroeder This has been fixed and published as v0.5.4 on npm :-)

**Comment by eiriklv** [comment]
Be sure to purge all your node_modules cache on heroku if you run your app there

**Comment by marcelopereirascmspain** [comment]
@eiriklv Thanks! 
Seems that the problem I was having with a weird top position has been fixed as well =)

**Comment by eiriklv** [comment]
@marcelopereirascmspain that's great! probably bco #3 :-)

**Comment by hugoeanogueira** [comment]
Thanks! xD

**Comment by colindresj** [comment]
@eiriklv this seems to be happening again. Any reason why you've chosen to use your own dependency forks?

**Comment by eiriklv** [comment]
@colindresj could you paste the specific issue? :-)

The reason for this is that the original dependencies are borked when using webpack, which defaults to AMD (if that part precedes the CommonJS part). @desandro wasn't keen on doing this fix on the originals - hence the mess..

**Comment by colindresj** [comment]
@eiriklv issue is noticeable when I try to `npm shrinkwrap`. I get an `extraneous: desandro-matches-selector@1.0.3` error.

It's traced back to:
`react-masonry mixin/node_modules/masonry/node_modules/outlayer/node_modules/desandro-matches-selector`

The `outlayer` module's package.json list's a dependency for `matches-selector` from a git url that points to desandro's matches-selector, which actually happens to be called `desandro-matches-selector`. That's outlayer@1.2.0. The current version of outlayer is 1.4.0, and it correctly points to an npm published version of  `desandro-matches-selector`. 

If you update your fork of `outlayer` or further up the tree, update your fork of `masonry`, we should be all good.

Hope I explained my problem well enough.

Thanks for the help.

**Comment by desandro** [comment]
I opened an issue with webpack webpack/webpack#883 about the larger problem of Webpack's behavior -- switching module formats based on what occurs first. Help address this issue and chime in there.

**Comment by colindresj** [comment]
@desandro Thanks for the issue. Getting that resolved would make it easier for @eiriklv to use your versions of masonry, etc. Though, for me, the immediate solution would be to bump dependencies. Is that something you can do @eiriklv?

**Comment by eiriklv** [comment]
@desandro @colindresj Yup - it would be great to be able to use the original dependencies directly, and there's probably a better solution for the interim as well, but for now I have just fixed the issues in the forks.

react-masonry-mixin@0.5.7
react-packery-mixin@0.1.9

**Comment by eiriklv** [comment]
@colindresj `npm shrinkwrap` should work now :-)

**Comment by colindresj** [comment]
Awesome @eiriklv Thanks for the fast response
